News/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('news_create/', NewsCreate.as_view(), name='CreateNews'),
    path('category_create', CategoryCreate.as_view(), name='CreateCategory'),
    path('news_remove/<pk>', RemoveNews.as_view(), name='RemoveNews'),
    path('news_update/<pk>', UpdateNews.as_view(), name='UpdateNews'),
    path('', ListNews.as_view(), name='ListNews'),
]

RExam/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.generic import RedirectView

from RExam import settings
from .views import AboutPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Accounts.urls')),
    path('news/', include('News.urls')),
    path('', RedirectView.as_view(permanent=False, url='news/'), name='HomePage'),
    path('about/', AboutPage.as_view(), name='AboutPage'),
    path('exams/', include('Exams.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

Accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
from django.urls import reverse


class StudyGroup(models.Model):
    group_name = models.CharField(max_length=10, blank=False, null=False, verbose_name=u'Имя группы')

    def __str__(self):
        return self.group_name

    def get_update_url(self):
        return reverse('StudyGroupUpdate', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('StudyGroupDelete', kwargs={'pk': self.id})

    class Meta:
        verbose_name = u'Учебная группа'
        verbose_name_plural = u'Учебные группы'


class UserAccount(AbstractUser):
    middle_name = models.CharField(max_length=20, blank=True, null=False, verbose_name=u'Отчество')
    study_group = models.ForeignKey(StudyGroup, on_delete=models.SET_NULL, null=True, blank=True)

    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = u'Пользователь'
        verbose_name_plural = u'Пользователи'

    def get_absolute_url(self):
        return reverse('Profile', kwargs={"pk": self.id})

    def get_update_url(self):
        return reverse('ProfileUpdate', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('ProfileDelete', kwargs={'pk': self.id})

RExam/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from News.models import News


class AboutPage(LoginRequiredMixin, TemplateView):
    template_name = 'RExam/About.html'

RExam/templates/RExam/About.html
{% extends 'RExam/BaseContent.html' %}
{% block head_title %}О сайте{% endblock head_title %}
{% block content %}
        <div class="card bg-light shadow-sm m-1">
        <p class="p-2">Сайт разработан для курсовой работы по ООП.</p>
        </div>
{% endblock content %}

RExam/templates/RExam/BaseContent.html
{% extends 'RExam/base.html' %}
{% block body_start %}
    <div class="d-flex justify-content-center h-100">
        <div class="container mt-lg-5">
            <nav class="navbar navbar-expand-lg navbar-dark bg-info menu shadow-sm m-1">
                <a class="navbar-brand" href="{% url 'HomePage' %}">RExam</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'HomePage' %}">Главная</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'ListExams' %}">Экзамены</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'AboutPage' %}">О сайте</a>
                        </li>
                        {% if user.is_staff %}
                            <li class="nav-item active dropdown">
                                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Управление</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    {% block control-item %}
                                    {% endblock control-item %}
                                    {% if perms.Accounts.view_useraccount %}
                                        <a class="dropdown-item" href="{% url 'UserList' %}">Пользователи</a>
                                    {% endif %}
                                    {% if perms.Accounts.view_studygroup %}
                                        <a class="dropdown-item" href="{% url 'StudyGroupList' %}">Учебные группы</a>
                                    {% endif %}
                                </div>
                            </li>
                        {% endif %}
                        {% block menu_items %}
                        {% endblock menu_items %}

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item dropdown align-right">
                            <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"><i class="far fa-user"></i>
                                {{ user.get_full_name }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'Profile' %}">Мой профиль</a>
                                <a class="dropdown-item" href="{% url 'ChangePassword' %}">Сменить пароль</a>
                                <a class="dropdown-item" href="">Статистика</a>
                                {% if user.is_staff %}<a class="dropdown-item" href="{% url 'admin:index' %}">Панель
                                    Администратора</a>{% endif %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'LogOut' %}">Выход</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            {% block content %}
                <div class="card bg-light shadow-sm m-1">

                    <div class="card-body"><p>Контент отсутсвует</p></div>

                </div>
            {% endblock content %}

            <div class="footer shadow-sm m-1">
                <div class="footer-content bg-info">Designed by DONit</div>
            </div>

        </div>
    </div>
{% endblock body_start %}

RExam/templates/RExam/ListTable.html
<table class="table table-bordered shadow-sm table-hover mt-3">
    <thead class="thead-light shadow-sm">
    <tr>
        {% block table_header %}{% endblock table_header %}
    </tr>
    </thead>
    <tbody>
        {% block table_body %}{% endblock table_body %}
    </tbody>
</table>

RExam/templates/RExam/RemoveBase.html
{% extends 'RExam/BaseContent.html' %}
{% block content %}
    <div class="card bg-light shadow-sm m-1">
        <form class="p-3" action="" method="POST">
            {% csrf_token %}
            <p>Вы действительно хотите удалить "{% block object_name %}{% endblock object_name %}" ?</p>
            <button type="submit" value="Confirm" class="btn btn-danger">Удалить</button>
        </form>
    </div>
{% endblock content %}

RExam/templates/RExam/base.html
{% load static %}
{% load fontawesome_5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <title>{% block head_title %}RExam{% endblock head_title %}</title>
    <link rel="stylesheet" href="{% static 'RExam/bootstrap/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'RExam/style.css' %}"/>
    {% fontawesome_5_static %}
    {% block head_end %}{% endblock head_end %}
</head>
<body>
{% block body_start %}
    <p><a href="{% url 'LogOut' %}">Выйти</a></p>
{% endblock body_start %}
<script src="{% static 'RExam/bootstrap/jquery-3.4.0.min.js' %}"></script>
<script src="{% static 'RExam/bootstrap/popper.min.js' %}"></script>
<script src="{% static 'RExam/bootstrap/bootstrap.min.js' %}"></script>
{% block body_end %}
{% endblock body_end %}
</body>
</html>