Exams/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('exams_list/', ListExams.as_view(), name='ListExams'),
    path('exam_create/', CreateExam.as_view(), name='CreateExam'),
    path('subject_create/', SubjectCreate.as_view(), name='SubjectCreate'),
    path('exam_detail/<pk>', ExamDetail.as_view(), name='ExamDetail'),
    path('exam_delete/<pk>', ExamDelete.as_view(), name='ExamDelete'),
    path('exam_update/<pk>', ExamUpdate.as_view(), name='ExamUpdate'),
    path('question_create/<int:exam_id>', QuestionCreate.as_view(), name='QuestionCreate'),
    path('question_delete/<pk>/<int:exam_id>', QuestionDelete.as_view(), name='QuestionDelete'),
    path('question_update/<pk>/<int:exam_id>', QuestionUpdate.as_view(), name='QuestionUpdate'),
    path('question_detail/<pk>', QuestionDetail.as_view(), name='QuestionDetail'),
    path('answer_create/<int:question_id>', AnswerCreate.as_view(), name='AnswerCreate'),
    path('answer_update/<pk>/<int:question_id>', AnswerUpdate.as_view(), name='AnswerUpdate'),
    path('answer_delete/<pk>/<int:question_id>', AnswerDelete.as_view(), name='AnswerDelete'),
    path('exam_start/<int:exam_id>', ExamAttempt.as_view(), name='ExamStart'),
    path('subject_list/', SubjectList.as_view(), name='SubjectList'),
    path('subject_update/<pk>', SubjectUpdate.as_view(), name='SubjectUpdate'),
    path('subject_delete/<pk>', SubjectDelete.as_view(), name='SubjectDelete'),
]

News/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('news_create/', NewsCreate.as_view(), name='CreateNews'),
    path('category_create', CategoryCreate.as_view(), name='CreateCategory'),
    path('news_remove/<pk>', RemoveNews.as_view(), name='RemoveNews'),
    path('news_update/<pk>', UpdateNews.as_view(), name='UpdateNews'),
    path('', ListNews.as_view(), name='ListNews'),
]

RExam/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.generic import RedirectView

from RExam import settings
from .views import AboutPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Accounts.urls')),
    path('news/', include('News.urls')),
    path('', RedirectView.as_view(permanent=False, url='news/'), name='HomePage'),
    path('about/', AboutPage.as_view(), name='AboutPage'),
    path('exams/', include('Exams.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

Exams/models.py
from django.db.models import Model, CharField, TextField, DateField, ForeignKey, SET_NULL, CASCADE, ImageField, \
    BooleanField
from django.http import Http404
from django.urls import reverse

from Accounts.models import UserAccount


class Subject(Model):
    name = CharField(max_length=30, blank=False, null=False, verbose_name=u'Имя предмета')

    def __str__(self):
        return self.name

    def get_delete_url(self):
        return reverse('SubjectDelete', kwargs={'pk': self.id})

    def get_update_url(self):
        return reverse('SubjectUpdate', kwargs={'pk': self.id})

    class Meta:
        verbose_name = u'Предмет'
        verbose_name_plural = u'Предметы'


class Exam(Model):
    exam_header = CharField(max_length=30, blank=False, null=False, verbose_name=u'Заголовок экзамена')
    exam_description = TextField(blank=False, null=True, verbose_name=u'Описание экзамена')
    exam_date = DateField(auto_now_add=True, blank=False, null=True, verbose_name=u'Дата создания')
    exam_subject = ForeignKey(Subject, blank=False, null=True, on_delete=SET_NULL, verbose_name=u'Предмет')
    exam_author = ForeignKey(UserAccount, blank=False, null=True, on_delete=SET_NULL, verbose_name=u'Автор')

    def __str__(self):
        return self.exam_header

    def get_detail_url(self):
        return reverse('ExamDetail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('ExamDelete', kwargs={'pk': self.id})

    def get_update_url(self):
        return reverse('ExamUpdate', kwargs={'pk': self.id})

    def get_add_question_url(self):
        return reverse('QuestionCreate', kwargs={'exam_id': self.id})

    def get_start_url(self):
        return reverse('ExamStart', kwargs={'exam_id': self.id})

    def get_question_set(self):
        if Question.objects.filter(question_exam=self.pk).exists():
            return Question.objects.filter(question_exam=self.pk)
        else:
            raise Http404("Вопросы по экзамену %s отсутствут" % self.exam_header)

    class Meta:
        verbose_name = u'Экзамен'
        verbose_name_plural = u'Экзамены'


class Question(Model):
    question_text = TextField(blank=False, null=False, verbose_name=u'Текст вопроса')
    question_exam = ForeignKey(Exam, blank=False, null=False, on_delete=CASCADE, verbose_name=u'Вопрос к экзамену')
    question_image = ImageField(upload_to='question_images', blank=True, null=True, verbose_name=u'Изображение вопроса')

    def __str__(self):
        return self.question_text

    def get_detail_url(self):
        return reverse('QuestionDetail', kwargs={'pk': self.id})

    def get_add_answer_url(self):
        return reverse('AnswerCreate', kwargs={'question_id': self.id})

    def get_delete_url(self):
        return reverse('QuestionDelete', kwargs={'pk': self.id, 'exam_id': self.question_exam.id})

    def get_update_url(self):
        return reverse('QuestionUpdate', kwargs={'pk': self.id, 'exam_id': self.question_exam.id})

    def get_answers_set(self):
        if Answer.objects.filter(answer_question=self.id).exists():
            return Answer.objects.filter(answer_question=self.id)
        else:
            raise Http404("Ответы по вопросу %s отсутствуют" % self.question_text)

    class Meta:
        verbose_name = u'Вопрос'
        verbose_name_plural = u'Вопросы'
        db_table = 'exam_questions'


class Answer(Model):
    answer_text = TextField(blank=False, null=False, verbose_name=u'Текст ответа')
    answer_question = ForeignKey(Question, blank=False, null=False, on_delete=CASCADE, verbose_name=u'Ответ к вопросу')
    answer_image = ImageField(upload_to='answer_images', blank=True, null=True, verbose_name=u'Изображение ответа')
    answer_truth = BooleanField(blank=False, null=False, verbose_name=u'Правильный ответ?')

    def get_delete_url(self):
        return reverse('AnswerDelete', kwargs={'pk': self.id, 'question_id': self.answer_question.id})

    def get_update_url(self):
        return reverse('AnswerUpdate', kwargs={'pk': self.id, 'question_id': self.answer_question.id})

    def __str__(self):
        return self.answer_text

    class Meta:
        verbose_name = u'Ответ'
        verbose_name_plural = u'Ответы'
        db_table = 'exam_answers'

Exams/forms.py
from django import forms
from django.forms import ModelForm, TextInput, Textarea, Select
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import safe

from Exams.models import Exam, Subject, Question, Answer


class ExamsCreateForm(ModelForm):
    class Meta:
        model = Exam
        fields = ('exam_subject', 'exam_header', 'exam_description')
        widgets = {
            'exam_header': TextInput(attrs={'class': 'form-control', 'placeholder': 'Заголовок'}),
            'exam_description': Textarea(attrs={'class': 'form-control', 'placeholder': 'Описание'}),
            'exam_subject': Select(attrs={'class': 'form-control col-5 d-inline', 'placeholder': 'Предмет'})
        }


class SubjectCreateForm(ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя предмета'})
        }


class QuestionCreateForm(ModelForm):
    class Meta:
        model = Question
        exclude = ['question_exam']
        widgets = {
            'question_text': Textarea(attrs={'class': 'form-control', 'placeholder': 'Текст вопроса'}),
        }


class AnswerCreateForm(ModelForm):
    class Meta:
        model = Answer
        exclude = ['answer_question']
        widgets = {
            'answer_text': Textarea(attrs={'class': 'form-control', 'placeholder': 'Текст ответа'}),
        }


class ExamAttemptForm(forms.Form):
    def __init__(self, *args, **kwargs):
        attempted_exam = get_object_or_404(Exam, pk=kwargs.pop('exam_id', None))
        questions = attempted_exam.get_question_set()
        super(ExamAttemptForm, self).__init__(*args, **kwargs)
        for question in questions:
            choices = []
            answers_set = question.get_answers_set()
            question_label = question.question_text
            if question.question_image:
                question_label += safe(
                    '<a target="_blank" rel="noopener noreferrer" href="' + question.question_image.url + '"><img class="d-block img-thumbnail rounded" width="500px" height="500px" src="' +
                    question.question_image.url + '"/></a>')
            for answer in answers_set:
                answer_choice = answer.answer_text
                if answer.answer_image:
                    answer_choice += '<a target="_blank" rel="noopener noreferrer" href="' + answer.answer_image.url + '"><img class="d-block img-thumbnail rounded" width="300px" height="300px" src="' + answer.answer_image.url + '"/></a>'

                choices.append((answer.pk, safe(answer_choice)))
            self.fields['question_%d' % question.pk] = forms.MultipleChoiceField(label=question_label,
                                                                                 required=True,
                                                                                 choices=choices,
                                                                                 widget=forms.CheckboxSelectMultiple)

Exams/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

# Create your views here.
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView, FormView

from Exams.forms import ExamsCreateForm, SubjectCreateForm, QuestionCreateForm, AnswerCreateForm, ExamAttemptForm
from Exams.models import Exam, Subject, Question, Answer


class ListExams(LoginRequiredMixin, ListView):
    model = Exam
    template_name = 'Exams/Exam/ExamsPage.html'


class CreateExam(PermissionRequiredMixin, CreateView):
    model = Exam
    form_class = ExamsCreateForm
    success_url = reverse_lazy('ListExams')
    permission_required = 'Exams.add_exam'
    template_name = 'Exams/Exam/ExamCreate.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.exam_author = self.request.user
        return super(CreateExam, self).form_valid(form)


class SubjectCreate(PermissionRequiredMixin, CreateView):
    model = Subject
    form_class = SubjectCreateForm
    success_url = reverse_lazy('CreateExam')
    permission_required = 'Exams.add_subject'
    template_name = 'Exams/Subject/SubjectCreate.html'


class SubjectUpdate(PermissionRequiredMixin, UpdateView):
    model = Subject
    form_class = SubjectCreateForm
    success_url = reverse_lazy('SubjectList')
    permission_required = 'Exams.change_subject'
    template_name = 'Exams/Subject/SubjectUpdate.html'


class SubjectList(PermissionRequiredMixin, ListView):
    model = Subject
    template_name = 'Exams/Subject/SubjectPage.html'
    permission_required = 'Exams.view_subject'


class SubjectDelete(PermissionRequiredMixin, DeleteView):
    model = Subject
    template_name = 'Exams/Subject/SubjectDelete.html'
    permission_required = 'Exams.delete_subject'
    success_url = reverse_lazy('SubjectList')


class ExamDetail(LoginRequiredMixin, DetailView):
    model = Exam
    template_name = 'Exams/Exam/ExamDetail.html'

    def get_context_data(self, **kwargs):
        context = super(ExamDetail, self).get_context_data(**kwargs)
        context['questions_list'] = Question.objects.filter(question_exam=self.kwargs['pk'])
        return context


class ExamDelete(PermissionRequiredMixin, DeleteView):
    model = Exam
    permission_required = 'Exams.delete_exam'
    success_url = reverse_lazy('ListExams')
    template_name = 'Exams/Exam/ExamDelete.html'


class ExamUpdate(PermissionRequiredMixin, UpdateView):
    model = Exam
    permission_required = 'Exams.change_exam'
    form_class = ExamsCreateForm
    template_name = 'Exams/Exam/ExamUpdate.html'

    def get_success_url(self):
        return reverse_lazy('ExamDetail', kwargs={'pk': self.kwargs['pk']})


class QuestionCreate(PermissionRequiredMixin, CreateView):
    model = Question
    permission_required = 'Exams.add_question'
    form_class = QuestionCreateForm
    template_name = 'Exams/Question/QuestionCreate.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.question_exam = get_object_or_404(Exam, pk=self.kwargs['exam_id'])
        return super(QuestionCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('ExamDetail', kwargs={'pk': self.kwargs['exam_id']})


class QuestionDelete(PermissionRequiredMixin, DeleteView):
    model = Question
    permission_required = 'Exams.delete_question'
    template_name = 'Exams/Question/QuestionDelete.html'

    def get_success_url(self):
        return reverse_lazy('ExamDetail', kwargs={'pk': self.kwargs['exam_id']})


class QuestionUpdate(PermissionRequiredMixin, UpdateView):
    model = Question
    form_class = QuestionCreateForm
    template_name = 'Exams/Question/QuestionUpdate.html'
    permission_required = 'Exam.change_question'

    def get_success_url(self):
        return reverse_lazy('ExamDetail', kwargs={'pk': self.kwargs['exam_id']})


class QuestionDetail(PermissionRequiredMixin, DetailView):
    model = Question
    template_name = 'Exams/Question/QuestionDetail.html'
    permission_required = 'Exams.view_question'

    def get_context_data(self, **kwargs):
        context = super(QuestionDetail, self).get_context_data(**kwargs)
        context['answers_list'] = Answer.objects.filter(answer_question=self.kwargs['pk'])
        return context


class AnswerCreate(PermissionRequiredMixin, CreateView):
    model = Answer
    form_class = AnswerCreateForm
    permission_required = 'Exams.add_answer'
    template_name = 'Exams/Answer/AnswerCreate.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.answer_question = Question.objects.get(pk=self.kwargs['question_id'])
        return super(AnswerCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('QuestionDetail', kwargs={'pk': self.kwargs['question_id']})


class AnswerUpdate(PermissionRequiredMixin, UpdateView):
    model = Answer
    form_class = AnswerCreateForm
    permission_required = 'Exams.change_answer'
    template_name = 'Exams/Answer/AnswerUpdate.html'

    def get_success_url(self):
        return reverse_lazy('QuestionDetail', kwargs={'pk': self.kwargs['question_id']})


class AnswerDelete(PermissionRequiredMixin, DeleteView):
    model = Answer
    permission_required = 'Exams.delete_answer'
    template_name = 'Exams/Answer/AnswerDelete.html'

    def get_success_url(self):
        return reverse_lazy('QuestionDetail', kwargs={'pk': self.kwargs['question_id']})


class ExamAttempt(FormView):
    form_class = ExamAttemptForm
    template_name = 'Exams/Exam/ExamForm.html'

    def get_success_url(self):
        return reverse_lazy('ExamDetail', kwargs={'pk': self.kwargs['exam_id']})

    def get_form_kwargs(self):
        kwargs = super(ExamAttempt, self).get_form_kwargs()
        kwargs['exam_id'] = self.kwargs['exam_id']
        return kwargs

    def form_valid(self, form):
        print(form.cleaned_data)
        return super(ExamAttempt, self).form_valid(form)

Exams/templates/Exams/Question/ListQuestions.html
{% extends 'RExam/ListTable.html' %}
{% block table_header %}
        <th style="width: 3%; text-align: center" scope="col">№</th>
        <th style="width: 60%;text-align: center" scope="col">Текст вопроса</th>
        <th style="text-align: center" scope="col">Изображение</th>
        {% if perms.Exams %}
            <th style="width: 15%;text-align: center" scope="col">Управление</th>
        {% endif %}
{% endblock table_header %}
{% block table_body %}
    {% for question in questions %}
        <tr>
            <th scope="row" class="text-center">{{ forloop.counter }}</th>
            <td><a href="{{ question.get_detail_url }}">{{ question.question_text }}</a></td>
            <td class="text-center">{% if not question.question_image %}-{% else %}
                <a class="text-info" href="{{ question.question_image.url }}">Изображение</a>{% endif %}</td>
            <td class="text-center">
                {% if perms.Exams.change_question %}
                    <a href="{{ question.get_update_url }}" class="text-primary mr-2">
                        <i class="fas fa-pen"></i>
                    </a>
                {% endif %}
                {% if perms.Exams.delete_question %}
                    <a class="text-danger" href="{{ question.get_delete_url }}"><i
                            class="fa fa-trash" aria-hidden="true"></i></a>
                {% endif %}
            </td>
        </tr>
    {% empty %}
        <tr>
            <th scope="row" class="text-center">1</th>
            <td><p class="pl-3">Вопросы отсутствуют...</p></td>
        </tr>
    {% endfor %}
{% endblock table_body %}

Exams/templates/Exams/Question/QuestionCreate.html
{% extends 'RExam/BaseContent.html' %}
{% block head_title %} Добавить вопрос {% endblock head_title %}
{% block content %}
    <div class="card bg-light shadow-sm m-1">
        <form class="p-4" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h5 class="text-center">Добавить вопрос</h5>
            {% for field in form %}
                    <div class="form-group">
                        <label class="d-block" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% if field.errors %}
                            <div class="alert alert-danger mt-2">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                    </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
                <button class="btn btn-success" type="submit">Добавить</button>
            </div>
        </form>
    </div>
{% endblock content %}

Exams/templates/Exams/Question/QuestionDelete.html
{% extends 'RExam/RemoveBase.html' %}
{% block head_title %} Удалить "{{ object.question_text }}" ? {% endblock %}
{% block object_name %}{{ object.question_text }} {% endblock object_name %}

Exams/templates/Exams/Question/QuestionDetail.html
{% extends 'RExam/BaseContent.html' %}
{% load static %}
{% block head_title %}{{ object.question_text }}{% endblock head_title %}
{% block head_end %}
    <link rel="stylesheet" href="{% static 'Exams/style.css' %}"/>
{% endblock head_end %}
{% block control-item %}
    {% if perms.Exams.add_answer %}
        <a class="dropdown-item" href="{{ object.get_add_answer_url }}"> Добавить ответ</a>
    {% endif %}
{% endblock control-item %}
{% block content %}
    <div class="card shadow-sm m-1">
        <div class="card-header shadow-sm">
            Описание вопроса
        </div>
        <div class="card-body">
            <p class="card-text">{{ object.question_text }}</p>
            {% if object.question_image %}<img class="shadow-sm rounded img-thumbnail img-fluid" src="{{ question.question_image.url }}" alt="{{ object.question_text }}"/>{% endif %}

            {% if perms.Exams.view_answer %}
                {% include "Exams/Answer/ListAnswers.html" with answers=answers_list question=object %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

Exams/templates/Exams/Question/QuestionUpdate.html
{% extends 'RExam/BaseContent.html' %}
{% block control-item %}{% endblock %}
{% block head_title %} Редактирование вопроса {% endblock head_title %}
{% block content %}
    <div class="card bg-light shadow-sm m-1">
        <form class="p-4" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h5 class="text-center">Редактирование вопроса</h5>
            {% for field in form %}
                <div class="form-group">
                    <label class="d-block" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="alert alert-danger mt-2">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
                <button class="btn btn-success" type="submit">Сохранить</button>
            </div>
        </form>
    </div>
{% endblock content %}